version: 2
updates:
  - package-ecosystem: "ruby:bundler"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "Dockerfile"
    directory: "/"
    schedule:
      interval: "daily"


