version: 2
jobs:
  tests:
    machine: true
    steps:
      - checkout
      - run: docker build -t salus-local .
      - run: docker build -f Dockerfile.tests -t salus-tests .
      - run: docker run salus-tests
      - run: bin/integration_test
  salus:
    machine: true
    steps:
      - checkout
      - run: docker run -t -v $(pwd):/home/repo coinbase/salus
  rubocop:
    docker:
      - image: ruby:2.4.5@sha256:a7a0a7c4dc2ea0ec483b52e9c30d360460c18cce04cebdaaba2aa0b94f9b0755
    steps:
      - checkout
      - run: apt-get update && apt-get install cmake -y
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rubocop

workflows:
  version: 2
  build:
    jobs:
      - tests
      - rubocop
      - salus
